name: Update README

on:
  schedule:
    # Run the job every day at midnight
    - cron: '*/1 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Last Updated Date in README
      run: python .github/scripts/update_readme.py
      
    - name: Commit and push if changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update README last updated date" || echo "No changes to commit"
        git push
